#include "finance/AnalyticsEngine.hpp"
#include "finance/FinanceService.hpp"
#include <algorithm>
#include <cctype>
#include <chrono>
#include <map>
#include <numeric>
#include <sstream>
namespace Pine::Finance {CashFlow AnalyticsEngine::cashFlow(const std::string&from,const std::string&to)const{CashFlow out;for(auto&t:service_.transactions("","","","","Posted",from,to,{}, {},100000)){if(t.type=="Income"||t.type=="Refund")out.income+=t.amount;else if(t.type=="Expense")out.expenses-=t.amount;}out.net=out.income-out.expenses;return out;}std::int64_t AnalyticsEngine::averageDailySpending(const std::string&from,const std::string&to)const{auto flow=cashFlow(from,to);std::chrono::sys_days a,b;std::istringstream(from)>>std::chrono::parse("%F",a);std::istringstream(to)>>std::chrono::parse("%F",b);auto days=std::max<std::int64_t>(1,(b-a).count()+1);return flow.expenses/days;}std::vector<Transaction>AnalyticsEngine::largestExpenses(const std::string&from,const std::string&to,std::size_t limit)const{auto rows=service_.transactions("","","","Expense","Posted",from,to,{}, {},100000);std::ranges::sort(rows,[](const auto&a,const auto&b){return std::llabs(a.amount)>std::llabs(b.amount);});if(rows.size()>limit)rows.resize(limit);return rows;}std::string AnalyticsEngine::normalizeMerchant(const std::string&source){std::string upper=source;std::ranges::transform(upper,upper.begin(),[](unsigned char c){return static_cast<char>(std::toupper(c));});const std::pair<const char*,const char*>known[]={{"SPOTIFY","Spotify"},{"NETFLIX","Netflix"},{"AMZN","Amazon"},{"WAL-MART","Walmart"},{"WALMART","Walmart"},{"UBER","Uber"},{"APPLE.COM/BILL","Apple"}};for(auto&[needle,name]:known)if(upper.find(needle)!=std::string::npos)return name;while(!upper.empty()&&(std::isdigit(static_cast<unsigned char>(upper.back()))||std::isspace(static_cast<unsigned char>(upper.back()))))upper.pop_back();return upper.empty()?source:upper;}std::vector<RecurringSuggestion>AnalyticsEngine::detectRecurring()const{std::map<std::string,std::vector<Transaction>>groups;for(auto&t:service_.transactions("","","","Expense","Posted","","",{}, {},100000))groups[normalizeMerchant(t.merchant)].push_back(t);std::vector<RecurringSuggestion>out;for(auto&[merchant,rows]:groups){if(merchant.empty()||rows.size()<3)continue;std::ranges::sort(rows,{},&Transaction::date);int monthly=0;for(std::size_t i=1;i<rows.size();++i){std::chrono::sys_days a,b;std::istringstream(rows[i-1].date)>>std::chrono::parse("%F",a);std::istringstream(rows[i].date)>>std::chrono::parse("%F",b);const auto gap=(b-a).count();const auto larger=std::max(std::llabs(rows[i].amount),std::llabs(rows[i-1].amount)),difference=std::llabs(std::llabs(rows[i].amount)-std::llabs(rows[i-1].amount));if(gap>=25&&gap<=35&&difference<=std::max<std::int64_t>(100,larger/20))++monthly;}if(monthly>=2){std::int64_t sum=0;for(auto&r:rows)sum+=std::llabs(r.amount);out.push_back({merchant,sum/static_cast<std::int64_t>(rows.size()),static_cast<int>(rows.size())});}}return out;}}
