#include "finance/FinanceService.hpp"
#include "finance/Money.hpp"
#include "core/Date.hpp"
#include "core/Logger.hpp"
#include <sqlite3.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <format>
#include <limits>
#include <random>
#include <stdexcept>

namespace Pine::Finance {
namespace {
using Clock=std::chrono::system_clock;std::int64_t now(){return std::chrono::duration_cast<std::chrono::milliseconds>(Clock::now().time_since_epoch()).count();}
void sqlCheck(int code,sqlite3*db){if(code!=SQLITE_OK&&code!=SQLITE_DONE&&code!=SQLITE_ROW)throw std::runtime_error(sqlite3_errmsg(db));}
struct Statement{sqlite3_stmt*s{};sqlite3*db{};Statement(sqlite3*d,const char*q):db(d){sqlCheck(sqlite3_prepare_v2(d,q,-1,&s,nullptr),d);}~Statement(){sqlite3_finalize(s);}void text(int i,const std::string&v){sqlCheck(sqlite3_bind_text(s,i,v.c_str(),-1,SQLITE_TRANSIENT),db);}void integer(int i,std::int64_t v){sqlCheck(sqlite3_bind_int64(s,i,v),db);}bool row(){auto c=sqlite3_step(s);if(c==SQLITE_ROW)return true;sqlCheck(c,db);return false;}void done(){sqlCheck(sqlite3_step(s),db);}};
std::string colText(sqlite3_stmt*s,int i){auto*t=sqlite3_column_text(s,i);return t?reinterpret_cast<const char*>(t):"";}
Account readAccount(sqlite3_stmt*s){return{colText(s,0),colText(s,1),colText(s,2),colText(s,3),colText(s,6),colText(s,7),colText(s,11),colText(s,12),sqlite3_column_int64(s,4),sqlite3_column_int64(s,5),sqlite3_column_int64(s,8),sqlite3_column_int64(s,9),sqlite3_column_int64(s,13),sqlite3_column_int64(s,14),sqlite3_column_int64(s,15),sqlite3_column_int64(s,16),sqlite3_column_int64(s,17),colText(s,18),sqlite3_column_int(s,10)!=0};}
Transaction readTransaction(sqlite3_stmt*s){return{colText(s,0),colText(s,1),colText(s,2),colText(s,4),colText(s,5),colText(s,6),colText(s,7),colText(s,8),colText(s,9),colText(s,12),colText(s,13),colText(s,14),colText(s,15),colText(s,16),sqlite3_column_int64(s,3),sqlite3_column_int64(s,10),sqlite3_column_int64(s,11)};}
constexpr const char*accountSelect="SELECT id,name,type,institution_name,current_balance,available_balance,currency,color_or_icon,created_at,updated_at,archived,sync_provider,sync_status,last_sync_time,credit_limit,statement_balance,minimum_payment,apr_basis_points,payment_due_date FROM accounts";
constexpr const char*transactionSelect="SELECT id,account_id,type,amount,currency,merchant,original_description,description,category,date,created_at,updated_at,status,notes,transfer_id,recurring_id,provider_transaction_id FROM transactions";
std::int64_t checkedAdd(std::int64_t left,std::int64_t right){if((right>0&&left>std::numeric_limits<std::int64_t>::max()-right)||(right<0&&left<std::numeric_limits<std::int64_t>::min()-right))throw std::overflow_error("Money amount overflow");return left+right;}
}
FinanceService::FinanceService(const std::filesystem::path&root):db_(root){seedCategories();}
std::string FinanceService::id(){static std::atomic_uint64_t seq{};return std::format("{:x}-{:x}",now(),seq++);}
std::string FinanceService::today(){return std::format("{:%Y-%m-%d}",std::chrono::floor<std::chrono::days>(Clock::now()));}
std::string FinanceService::currentMonth(){return today().substr(0,7);}
void FinanceService::seedCategories(){const std::pair<const char*,const char*>values[]={{"Food & Dining","FD"},{"Groceries","GR"},{"Gas","GA"},{"Transportation","TR"},{"Shopping","SH"},{"Entertainment","EN"},{"Housing","HO"},{"Utilities","UT"},{"Phone","PH"},{"Internet","IN"},{"Insurance","IS"},{"Healthcare","HC"},{"Education","ED"},{"Travel","TV"},{"Personal Care","PC"},{"Subscriptions","SU"},{"Fees","FE"},{"Taxes","TX"},{"Gifts","GI"},{"Income","+$"},{"Transfers","<>"},{"Other","OT"}};std::scoped_lock lock(db_.mutex());for(auto&[name,icon]:values){Statement s(db_.handle(),"INSERT OR IGNORE INTO categories(id,name,icon,built_in,hidden) VALUES(?,?,?,?,0)");s.text(1,std::string("builtin-")+icon);s.text(2,name);s.text(3,icon);s.integer(4,1);s.done();}}
Account FinanceService::createAccount(std::string name,std::string type,std::string institution,std::int64_t balance,std::string currency){if(name.empty())throw std::invalid_argument("Account name is required");Account a;const auto t=now();a.id=id();a.name=std::move(name);a.type=std::move(type);a.institution=std::move(institution);a.currency=Currency::fromCode(std::move(currency)).code;a.currentBalance=a.availableBalance=balance;a.createdAt=a.updatedAt=t;db_.transaction([&]{Statement s(db_.handle(),"INSERT INTO accounts(id,name,type,institution_name,current_balance,available_balance,currency,color_or_icon,created_at,updated_at,archived,sync_provider,sync_status,last_sync_time)VALUES(?,?,?,?,?,?,?,?,?,?,0,'manual','Manual',0)");s.text(1,a.id);s.text(2,a.name);s.text(3,a.type);s.text(4,a.institution);s.integer(5,balance);s.integer(6,balance);s.text(7,a.currency);s.text(8,a.color);s.integer(9,t);s.integer(10,t);s.done();snapshotIfNeeded(a.id,balance);});return a;}
bool FinanceService::updateAccount(const Account&a){std::scoped_lock lock(db_.mutex());Statement s(db_.handle(),"UPDATE accounts SET name=?,type=?,institution_name=?,available_balance=?,currency=?,credit_limit=?,statement_balance=?,minimum_payment=?,apr_basis_points=?,payment_due_date=?,updated_at=? WHERE id=?");s.text(1,a.name);s.text(2,a.type);s.text(3,a.institution);s.integer(4,a.availableBalance);s.text(5,a.currency);s.integer(6,a.creditLimit);s.integer(7,a.statementBalance);s.integer(8,a.minimumPayment);s.integer(9,a.aprBasisPoints);s.text(10,a.paymentDueDate);s.integer(11,now());s.text(12,a.id);s.done();return sqlite3_changes(db_.handle())>0;}
bool FinanceService::archiveAccount(const std::string&idValue,bool archived){std::scoped_lock lock(db_.mutex());Statement s(db_.handle(),"UPDATE accounts SET archived=?,updated_at=? WHERE id=?");s.integer(1,archived);s.integer(2,now());s.text(3,idValue);s.done();return sqlite3_changes(db_.handle())>0;}
std::optional<Account>FinanceService::account(const std::string&idValue)const{std::scoped_lock lock(const_cast<FinanceDatabase&>(db_).mutex());Statement s(db_.handle(),(std::string(accountSelect)+" WHERE id=?").c_str());s.text(1,idValue);if(!s.row())return{};return readAccount(s.s);}
std::vector<Account>FinanceService::accounts(bool archived)const{std::scoped_lock lock(const_cast<FinanceDatabase&>(db_).mutex());Statement s(db_.handle(),(std::string(accountSelect)+(archived?" ORDER BY archived,name":" WHERE archived=0 ORDER BY name")).c_str());std::vector<Account>out;while(s.row())out.push_back(readAccount(s.s));return out;}
void FinanceService::snapshotIfNeeded(const std::string&accountId,std::int64_t balance){Statement last(db_.handle(),"SELECT balance,timestamp FROM balance_snapshots WHERE account_id=? ORDER BY timestamp DESC,id DESC LIMIT 1");last.text(1,accountId);bool write=true;if(last.row()){const auto old=sqlite3_column_int64(last.s,0),time=sqlite3_column_int64(last.s,1);write=(balance>=old?static_cast<std::uint64_t>(balance)-static_cast<std::uint64_t>(old):static_cast<std::uint64_t>(old)-static_cast<std::uint64_t>(balance))>=100||now()-time>=86400000;}if(write){Statement s(db_.handle(),"INSERT INTO balance_snapshots(account_id,balance,timestamp)VALUES(?,?,?)");s.text(1,accountId);s.integer(2,balance);s.integer(3,now());s.done();}}
Transaction FinanceService::addTransaction(std::string accountId,std::string type,std::int64_t amount,std::string merchant,std::string category,std::string date,std::string notes,std::string status){std::scoped_lock lock(db_.mutex());auto a=account(accountId);if(!a)throw std::invalid_argument("Account not found");if(amount<=0)throw std::invalid_argument("Amount must be positive");if(type!="Expense"&&type!="Income"&&type!="Refund"&&type!="Adjustment")throw std::invalid_argument("Unsupported transaction type");Transaction t;const auto stamp=now();t.id=id();t.accountId=std::move(accountId);t.type=std::move(type);t.amount=(t.type=="Expense"?-amount:amount);const auto resultingBalance=checkedAdd(a->currentBalance,t.amount);checkedAdd(a->availableBalance,t.amount);t.currency=a->currency;t.merchant=std::move(merchant);t.originalDescription=t.merchant;t.category=category.empty()?"Other":std::move(category);t.date=date.empty()?today():std::move(date);Pine::parseIsoDate(t.date);t.notes=std::move(notes);t.status=std::move(status);t.createdAt=t.updatedAt=stamp;db_.transaction([&]{Statement s(db_.handle(),"INSERT INTO transactions(id,account_id,type,amount,currency,merchant,original_description,description,category,date,created_at,updated_at,status,notes)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");s.text(1,t.id);s.text(2,t.accountId);s.text(3,t.type);s.integer(4,t.amount);s.text(5,t.currency);s.text(6,t.merchant);s.text(7,t.originalDescription);s.text(8,t.description);s.text(9,t.category);s.text(10,t.date);s.integer(11,stamp);s.integer(12,stamp);s.text(13,t.status);s.text(14,t.notes);s.done();Statement u(db_.handle(),"UPDATE accounts SET current_balance=current_balance+?,available_balance=available_balance+?,updated_at=? WHERE id=?");u.integer(1,t.amount);u.integer(2,t.amount);u.integer(3,stamp);u.text(4,t.accountId);u.done();snapshotIfNeeded(t.accountId,resultingBalance);});return t;}
std::pair<Transaction,Transaction>FinanceService::transfer(const std::string&from,const std::string&to,std::int64_t amount,std::string date,std::string notes){std::scoped_lock lock(db_.mutex());if(from==to||amount<=0)throw std::invalid_argument("Invalid transfer");auto source=account(from),target=account(to);if(!source||!target||source->currency!=target->currency)throw std::invalid_argument("Transfer accounts must exist and share currency");const auto sourceBalance=checkedAdd(source->currentBalance,-amount),targetBalance=checkedAdd(target->currentBalance,amount);checkedAdd(source->availableBalance,-amount);checkedAdd(target->availableBalance,amount);Pine::parseIsoDate(date.empty()?today():date);const auto stamp=now();const auto link=id();Transaction out{id(),from,"Transfer",source->currency,"Transfer","Transfer","Transfer to "+target->name,"Transfers",date.empty()?today():date,"Posted",notes,link,"","",-amount,stamp,stamp};Transaction in{id(),to,"Transfer",target->currency,"Transfer","Transfer","Transfer from "+source->name,"Transfers",out.date,"Posted",notes,link,"","",amount,stamp,stamp};db_.transaction([&]{for(const auto*t:{&out,&in}){Statement s(db_.handle(),"INSERT INTO transactions(id,account_id,type,amount,currency,merchant,original_description,description,category,date,created_at,updated_at,status,notes,transfer_id)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");s.text(1,t->id);s.text(2,t->accountId);s.text(3,t->type);s.integer(4,t->amount);s.text(5,t->currency);s.text(6,t->merchant);s.text(7,t->originalDescription);s.text(8,t->description);s.text(9,t->category);s.text(10,t->date);s.integer(11,stamp);s.integer(12,stamp);s.text(13,t->status);s.text(14,t->notes);s.text(15,link);s.done();Statement u(db_.handle(),"UPDATE accounts SET current_balance=current_balance+?,available_balance=available_balance+?,updated_at=? WHERE id=?");u.integer(1,t->amount);u.integer(2,t->amount);u.integer(3,stamp);u.text(4,t->accountId);u.done();}snapshotIfNeeded(from,sourceBalance);snapshotIfNeeded(to,targetBalance);});return{out,in};}
bool FinanceService::deleteTransaction(const std::string& idValue) {
    bool found=false;
    db_.transaction([&] {
        Statement target(db_.handle(),(std::string(transactionSelect)+" WHERE id=?").c_str());
        target.text(1,idValue); if(!target.row())return;
        const auto t=readTransaction(target.s); found=true;
        std::vector<Transaction> rows{t};
        if(!t.transferId.empty()) {
            rows.clear(); Statement linked(db_.handle(),(std::string(transactionSelect)+" WHERE transfer_id=?").c_str());
            linked.text(1,t.transferId); while(linked.row())rows.push_back(readTransaction(linked.s));
        }
        for(const auto& row:rows) {
            auto a=account(row.accountId); if(!a)throw std::runtime_error("Transaction account missing");
            auto balance=(Money{a->currentBalance,{}}-Money{row.amount,{}}).minor;
            auto available=(Money{a->availableBalance,{}}-Money{row.amount,{}}).minor;
            Statement update(db_.handle(),"UPDATE accounts SET current_balance=?,available_balance=?,updated_at=? WHERE id=?");
            update.integer(1,balance);update.integer(2,available);update.integer(3,now());update.text(4,a->id);update.done();
            Statement remove(db_.handle(),"DELETE FROM transactions WHERE id=?");remove.text(1,row.id);remove.done();
            snapshotIfNeeded(a->id,balance);
        }
    });
    return found;
}
Transaction FinanceService::reconcile(const std::string& accountId,std::int64_t actual,std::string date) {
    Transaction result;
    db_.transaction([&] {
        auto a=account(accountId);if(!a)throw std::invalid_argument("Account not found");
        const auto difference=(Money{actual,{}}-Money{a->currentBalance,{}}).minor;
        if(difference==0)throw std::invalid_argument("Balance already reconciled");
        if(difference==std::numeric_limits<std::int64_t>::min())throw std::overflow_error("Reconciliation amount too large");
        result=addTransaction(accountId,difference<0?"Expense":"Adjustment",difference<0?-difference:difference,
            "Balance reconciliation","Other",std::move(date),"Manual reconciliation");
        Statement update(db_.handle(),"UPDATE transactions SET type='Adjustment' WHERE id=?");update.text(1,result.id);update.done();
        result.type="Adjustment";
    });
    return result;
}
std::vector<Transaction>FinanceService::transactions(std::string search,std::string accountId,std::string category,std::string type,std::string status,std::string from,std::string to,std::optional<std::int64_t>min,std::optional<std::int64_t>max,std::size_t limit,std::size_t offset)const{std::string q=std::string(transactionSelect)+" WHERE 1=1";std::vector<std::string>textValues;if(!search.empty()){q+=" AND (merchant LIKE ? OR description LIKE ? OR notes LIKE ? OR category LIKE ?)";for(int i=0;i<4;++i)textValues.push_back("%"+search+"%");}for(auto&[column,value]:std::initializer_list<std::pair<const char*,std::string*>>{{"account_id",&accountId},{"category",&category},{"type",&type},{"status",&status}})if(!value->empty()){q+=std::string(" AND ")+column+"=?";textValues.push_back(*value);}if(!from.empty()){q+=" AND date>=?";textValues.push_back(from);}if(!to.empty()){q+=" AND date<=?";textValues.push_back(to);}if(min)q+=" AND ABS(amount)>=?";if(max)q+=" AND ABS(amount)<=?";q+=" ORDER BY date DESC,created_at DESC LIMIT ? OFFSET ?";std::scoped_lock lock(const_cast<FinanceDatabase&>(db_).mutex());Statement s(db_.handle(),q.c_str());int i=1;for(auto&v:textValues)s.text(i++,v);if(min)s.integer(i++,*min);if(max)s.integer(i++,*max);s.integer(i++,static_cast<std::int64_t>(std::min<std::size_t>(limit,100000)));s.integer(i++,static_cast<std::int64_t>(offset));std::vector<Transaction>out;while(s.row())out.push_back(readTransaction(s.s));return out;}
Category FinanceService::createCategory(std::string name,std::string icon){if(name.empty())throw std::invalid_argument("Category name is required");Category c{id(),std::move(name),icon.empty()?"OT":std::move(icon),false,false};std::scoped_lock lock(db_.mutex());Statement s(db_.handle(),"INSERT INTO categories(id,name,icon,built_in,hidden)VALUES(?,?,?,0,0)");s.text(1,c.id);s.text(2,c.name);s.text(3,c.icon);s.done();return c;}
bool FinanceService::renameCategory(const std::string&idValue,const std::string&name){if(name.empty())return false;db_.transaction([&]{Statement q(db_.handle(),"SELECT name,built_in FROM categories WHERE id=?");q.text(1,idValue);if(!q.row()||sqlite3_column_int(q.s,1))throw std::invalid_argument("Only custom categories may be renamed");auto old=colText(q.s,0);Statement t(db_.handle(),"UPDATE transactions SET category=? WHERE category=?");t.text(1,name);t.text(2,old);t.done();Statement b(db_.handle(),"UPDATE budgets SET category=? WHERE category=?");b.text(1,name);b.text(2,old);b.done();Statement c(db_.handle(),"UPDATE categories SET name=? WHERE id=?");c.text(1,name);c.text(2,idValue);c.done();});return true;}
bool FinanceService::hideCategory(const std::string&idValue,bool hidden){std::scoped_lock lock(db_.mutex());Statement s(db_.handle(),"UPDATE categories SET hidden=? WHERE id=?");s.integer(1,hidden);s.text(2,idValue);s.done();return sqlite3_changes(db_.handle())>0;}
std::vector<Category>FinanceService::categories(bool hidden)const{std::scoped_lock lock(const_cast<FinanceDatabase&>(db_).mutex());Statement s(db_.handle(),hidden?"SELECT id,name,icon,built_in,hidden FROM categories ORDER BY built_in DESC,name":"SELECT id,name,icon,built_in,hidden FROM categories WHERE hidden=0 ORDER BY built_in DESC,name");std::vector<Category>out;while(s.row())out.push_back({colText(s.s,0),colText(s.s,1),colText(s.s,2),sqlite3_column_int(s.s,3)!=0,sqlite3_column_int(s.s,4)!=0});return out;}
Budget FinanceService::setBudget(std::string category,std::string month,std::int64_t limit,bool rollover,int warning){if(limit<0)throw std::invalid_argument("Budget must not be negative");if(!month.empty())Pine::parseIsoDate(month+"-01");Budget b{id(),std::move(category),month.empty()?currentMonth():std::move(month),limit,rollover,std::clamp(warning,1,100)};std::scoped_lock lock(db_.mutex());Statement s(db_.handle(),"INSERT INTO budgets(id,category,month,limit_minor,rollover,warning_percent)VALUES(?,?,?,?,?,?) ON CONFLICT(category,month) DO UPDATE SET limit_minor=excluded.limit_minor,rollover=excluded.rollover,warning_percent=excluded.warning_percent");s.text(1,b.id);s.text(2,b.category);s.text(3,b.month);s.integer(4,b.limit);s.integer(5,b.rollover);s.integer(6,b.warningPercent);s.done();Statement stored(db_.handle(),"SELECT id FROM budgets WHERE category=? AND month=?");stored.text(1,b.category);stored.text(2,b.month);if(stored.row())b.id=colText(stored.s,0);return b;}
bool FinanceService::deleteBudget(const std::string&idValue){std::scoped_lock lock(db_.mutex());Statement s(db_.handle(),"DELETE FROM budgets WHERE id=?");s.text(1,idValue);s.done();return sqlite3_changes(db_.handle())>0;}
std::vector<Budget>FinanceService::budgets(std::string month)const{std::scoped_lock lock(const_cast<FinanceDatabase&>(db_).mutex());Statement s(db_.handle(),month.empty()?"SELECT id,category,month,limit_minor,rollover,warning_percent FROM budgets ORDER BY month DESC,category":"SELECT id,category,month,limit_minor,rollover,warning_percent FROM budgets WHERE month=? ORDER BY category");if(!month.empty())s.text(1,month);std::vector<Budget>out;while(s.row())out.push_back({colText(s.s,0),colText(s.s,1),colText(s.s,2),sqlite3_column_int64(s.s,3),sqlite3_column_int(s.s,4)!=0,sqlite3_column_int(s.s,5)});return out;}
std::int64_t FinanceService::budgetSpent(const Budget&b)const{std::scoped_lock lock(const_cast<FinanceDatabase&>(db_).mutex());Statement s(db_.handle(),"SELECT COALESCE(-SUM(amount),0) FROM transactions WHERE type='Expense' AND status='Posted' AND category=? AND substr(date,1,7)=? AND currency=?");s.text(1,b.category);s.text(2,b.month);s.text(3,settings().defaultCurrency);return s.row()?sqlite3_column_int64(s.s,0):0;}
std::int64_t FinanceService::budgetAvailable(const Budget&b)const{auto available=b.limit-budgetSpent(b);if(!b.rollover)return available;auto month=std::chrono::year_month(std::chrono::year(std::stoi(b.month.substr(0,4))),std::chrono::month(std::stoi(b.month.substr(5,2))));auto prior=month-std::chrono::months(1);auto key=std::format("{:04}-{:02}",int(prior.year()),unsigned(prior.month()));auto previous=budgets(key);auto it=std::ranges::find(previous,b.category,&Budget::category);return it==previous.end()?available:available+std::max<std::int64_t>(0,it->limit-budgetSpent(*it));}
#define FINANCE_SIMPLE_DELETE(method,table) bool FinanceService::method(const std::string&idValue){std::scoped_lock lock(db_.mutex());Statement s(db_.handle(),"DELETE FROM " table " WHERE id=?");s.text(1,idValue);s.done();return sqlite3_changes(db_.handle())>0;}
Bill FinanceService::addBill(std::string name,std::int64_t amount,std::string accountId,std::string category,std::string due,std::string frequency,bool autopay,bool reminder,int days,std::string notes){Pine::parseIsoDate(due);if(name.empty()||amount<=0)throw std::invalid_argument("Bill name and positive amount required");Bill b{id(),std::move(name),std::move(accountId),std::move(category),std::move(frequency),std::move(due),std::move(notes),amount,autopay,reminder,std::max(0,days)};std::scoped_lock lock(db_.mutex());Statement s(db_.handle(),"INSERT INTO bills(id,name,amount_minor,account_id,category,next_due_date,frequency,autopay,reminder_enabled,reminder_days,notes)VALUES(?,?,?,?,?,?,?,?,?,?,?)");s.text(1,b.id);s.text(2,b.name);s.integer(3,b.amount);s.text(4,b.accountId);s.text(5,b.category);s.text(6,b.nextDueDate);s.text(7,b.frequency);s.integer(8,b.autopay);s.integer(9,b.reminderEnabled);s.integer(10,b.reminderDays);s.text(11,b.notes);s.done();return b;}
FINANCE_SIMPLE_DELETE(deleteBill,"bills")
std::vector<Bill>FinanceService::bills()const{std::scoped_lock lock(const_cast<FinanceDatabase&>(db_).mutex());Statement s(db_.handle(),"SELECT id,name,account_id,category,frequency,next_due_date,notes,amount_minor,autopay,reminder_enabled,reminder_days FROM bills ORDER BY next_due_date");std::vector<Bill>out;while(s.row())out.push_back({colText(s.s,0),colText(s.s,1),colText(s.s,2),colText(s.s,3),colText(s.s,4),colText(s.s,5),colText(s.s,6),sqlite3_column_int64(s.s,7),sqlite3_column_int(s.s,8)!=0,sqlite3_column_int(s.s,9)!=0,sqlite3_column_int(s.s,10)});return out;}
Subscription FinanceService::addSubscription(std::string name,std::int64_t price,std::string frequency,std::string accountId,std::string nextCharge,std::string category){Pine::parseIsoDate(nextCharge);if(name.empty()||price<=0)throw std::invalid_argument("Subscription name and positive price required");Subscription s{id(),std::move(name),std::move(frequency),std::move(accountId),std::move(nextCharge),std::move(category),price,true};std::scoped_lock lock(db_.mutex());Statement q(db_.handle(),"INSERT INTO subscriptions(id,name,price_minor,frequency,account_id,next_charge,category,active)VALUES(?,?,?,?,?,?,?,1)");q.text(1,s.id);q.text(2,s.name);q.integer(3,s.price);q.text(4,s.frequency);q.text(5,s.accountId);q.text(6,s.nextCharge);q.text(7,s.category);q.done();return s;}
FINANCE_SIMPLE_DELETE(deleteSubscription,"subscriptions")
std::vector<Subscription>FinanceService::subscriptions(bool active)const{std::scoped_lock lock(const_cast<FinanceDatabase&>(db_).mutex());Statement s(db_.handle(),active?"SELECT id,name,frequency,account_id,next_charge,category,price_minor,active FROM subscriptions WHERE active=1 ORDER BY next_charge":"SELECT id,name,frequency,account_id,next_charge,category,price_minor,active FROM subscriptions ORDER BY next_charge");std::vector<Subscription>out;while(s.row())out.push_back({colText(s.s,0),colText(s.s,1),colText(s.s,2),colText(s.s,3),colText(s.s,4),colText(s.s,5),sqlite3_column_int64(s.s,6),sqlite3_column_int(s.s,7)!=0});return out;}
Goal FinanceService::addGoal(std::string name,std::int64_t target,std::string date,std::string linked){if(name.empty()||target<=0)throw std::invalid_argument("Goal name and positive target required");if(!date.empty())Pine::parseIsoDate(date);Goal g{id(),std::move(name),std::move(date),std::move(linked),target,0,now(),false};std::scoped_lock lock(db_.mutex());Statement s(db_.handle(),"INSERT INTO goals(id,name,target_amount,current_amount,target_date,linked_account_id,created_at,completed)VALUES(?,?,?,?,?,?,?,0)");s.text(1,g.id);s.text(2,g.name);s.integer(3,g.targetAmount);s.integer(4,0);s.text(5,g.targetDate);s.text(6,g.linkedAccountId);s.integer(7,g.createdAt);s.done();return g;}
bool FinanceService::contribute(const std::string&idValue,std::int64_t amount){if(amount<=0)return false;db_.transaction([&]{Statement existing(db_.handle(),"SELECT current_amount FROM goals WHERE id=?");existing.text(1,idValue);if(!existing.row())throw std::invalid_argument("Goal not found");checkedAdd(sqlite3_column_int64(existing.s,0),amount);Statement c(db_.handle(),"INSERT INTO goal_contributions(id,goal_id,amount_minor,created_at)VALUES(?,?,?,?)");c.text(1,id());c.text(2,idValue);c.integer(3,amount);c.integer(4,now());c.done();Statement g(db_.handle(),"UPDATE goals SET current_amount=current_amount+?,completed=(current_amount+?>=target_amount) WHERE id=? AND linked_account_id=''");g.integer(1,amount);g.integer(2,amount);g.text(3,idValue);g.done();if(sqlite3_changes(db_.handle())==0)throw std::invalid_argument("Linked goals derive progress from account balance");});return true;}
FINANCE_SIMPLE_DELETE(deleteGoal,"goals")
std::vector<Goal>FinanceService::goals(bool completed)const{std::vector<Goal>out;{std::scoped_lock lock(const_cast<FinanceDatabase&>(db_).mutex());Statement s(db_.handle(),completed?"SELECT id,name,target_date,linked_account_id,target_amount,current_amount,created_at,completed FROM goals ORDER BY completed,name":"SELECT id,name,target_date,linked_account_id,target_amount,current_amount,created_at,completed FROM goals WHERE completed=0 ORDER BY name");while(s.row())out.push_back({colText(s.s,0),colText(s.s,1),colText(s.s,2),colText(s.s,3),sqlite3_column_int64(s.s,4),sqlite3_column_int64(s.s,5),sqlite3_column_int64(s.s,6),sqlite3_column_int(s.s,7)!=0});}for(auto&g:out)if(!g.linkedAccountId.empty())if(auto a=account(g.linkedAccountId))g.currentAmount=std::max<std::int64_t>(0,a->currentBalance);return out;}
DashboardSummary FinanceService::dashboard(std::string month)const {
    if(month.empty())month=currentMonth();
    const auto config=settings();DashboardSummary d;
    for(const auto& a:accounts()) {
        if(a.currency!=config.defaultCurrency)continue;
        if(a.type=="Credit Card"||a.type=="Loan"||a.type=="Other Liability") {
            if(a.currentBalance==std::numeric_limits<std::int64_t>::min())throw std::overflow_error("Liability total too large");
            d.liabilities=checkedAdd(d.liabilities,std::llabs(a.currentBalance));
        } else d.assets=checkedAdd(d.assets,a.currentBalance);
    }
    d.netWorth=(Money{d.assets,{}}-Money{d.liabilities,{}}).minor;
    {
        std::scoped_lock lock(const_cast<FinanceDatabase&>(db_).mutex());
        Statement cash(db_.handle(),"SELECT COALESCE(SUM(CASE WHEN type IN('Income','Refund') THEN amount ELSE 0 END),0),COALESCE(-SUM(CASE WHEN type='Expense' THEN amount ELSE 0 END),0) FROM transactions WHERE status='Posted' AND substr(date,1,7)=? AND currency=?");
        cash.text(1,month);cash.text(2,config.defaultCurrency);
        if(cash.row()){d.incomeMonth=sqlite3_column_int64(cash.s,0);d.spendingMonth=sqlite3_column_int64(cash.s,1);}
        Statement budget(db_.handle(),"SELECT COALESCE(SUM(limit_minor),0) FROM budgets WHERE month=?");budget.text(1,month);if(budget.row())d.budgetLimit=sqlite3_column_int64(budget.s,0);
    }
    if(config.totalMonthlyBudget>0)d.budgetLimit=config.totalMonthlyBudget;
    d.budgetRemaining=(Money{d.budgetLimit,{}}-Money{d.spendingMonth,{}}).minor;
    for(const auto& s:subscriptions()) {
        if(!s.accountId.empty()){auto a=account(s.accountId);if(a&&a->currency!=config.defaultCurrency)continue;}
        auto monthly=s.price;
        if(s.frequency=="Yearly")monthly=s.price/12;
        else if(s.frequency=="Weekly") {
            if(s.price>std::numeric_limits<std::int64_t>::max()/52)throw std::overflow_error("Subscription total too large");
            monthly=s.price*52/12;
        }
        d.subscriptionMonthly=checkedAdd(d.subscriptionMonthly,monthly);
    }
    return d;
}
std::vector<CategorySpend>FinanceService::spendingByCategory(std::string from,std::string to,std::size_t limit)const{std::scoped_lock lock(const_cast<FinanceDatabase&>(db_).mutex());Statement s(db_.handle(),"SELECT category,-SUM(amount) total FROM transactions WHERE type='Expense' AND status='Posted' AND date>=? AND date<=? AND currency=? GROUP BY category ORDER BY total DESC LIMIT ?");s.text(1,from);s.text(2,to);s.text(3,settings().defaultCurrency);s.integer(4,limit);std::vector<CategorySpend>out;while(s.row())out.push_back({colText(s.s,0),sqlite3_column_int64(s.s,1)});return out;}
std::vector<BalanceSnapshot>FinanceService::balanceHistory(const std::string&accountId,std::size_t limit)const{std::scoped_lock lock(const_cast<FinanceDatabase&>(db_).mutex());Statement s(db_.handle(),"SELECT account_id,balance,timestamp FROM balance_snapshots WHERE account_id=? ORDER BY timestamp DESC,id DESC LIMIT ?");s.text(1,accountId);s.integer(2,limit);std::vector<BalanceSnapshot>out;while(s.row())out.push_back({colText(s.s,0),sqlite3_column_int64(s.s,1),sqlite3_column_int64(s.s,2)});return out;}
FinanceSettings FinanceService::settings()const{std::scoped_lock lock(const_cast<FinanceDatabase&>(db_).mutex());FinanceSettings out;Statement s(db_.handle(),"SELECT key,value FROM finance_settings");while(s.row()){auto key=colText(s.s,0),v=colText(s.s,1);if(key=="currency")out.defaultCurrency=v;else if(key=="auto_lock")out.autoLock=v;else if(key=="week_start")out.weekStart=v;else if(key=="hide_balances")out.hideBalances=v=="1";else if(key=="require_auth")out.requireAuthentication=v=="1";else if(key=="notification_previews")out.notificationPreviews=v=="1";else if(key=="notifications")out.notificationsEnabled=v=="1";else if(key=="total_budget")out.totalMonthlyBudget=std::stoll(v);else if(key=="warning")out.budgetWarningPercent=std::stoi(v);else if(key=="dashboard_mask")out.dashboardMask=std::stoi(v);}return out;}
void FinanceService::saveSettings(const FinanceSettings&v){db_.transaction([&]{auto put=[&](const char*k,std::string value){Statement s(db_.handle(),"INSERT INTO finance_settings(key,value)VALUES(?,?) ON CONFLICT(key)DO UPDATE SET value=excluded.value");s.text(1,k);s.text(2,value);s.done();};put("currency",v.defaultCurrency);put("auto_lock",v.autoLock);put("week_start",v.weekStart);put("hide_balances",v.hideBalances?"1":"0");put("require_auth",v.requireAuthentication?"1":"0");put("notification_previews",v.notificationPreviews?"1":"0");put("notifications",v.notificationsEnabled?"1":"0");put("total_budget",std::to_string(v.totalMonthlyBudget));put("warning",std::to_string(v.budgetWarningPercent));put("dashboard_mask",std::to_string(v.dashboardMask));});}
void FinanceService::eraseAll(){db_.transaction([&]{for(auto table:{"goal_contributions","goals","subscriptions","bills","budgets","transactions","balance_snapshots","accounts","import_fingerprints","sync_connections","finance_settings"})db_.execute(std::string("DELETE FROM ")+table);});}
}
