#include "finance/ImportExportManager.hpp"
#include "finance/FinanceService.hpp"
#include "finance/Money.hpp"
#include "services/FileService.hpp"
#include <nlohmann/json.hpp>
#include <sqlite3.h>
#include <fstream>
#include <format>
#include <sstream>
#include <stdexcept>

namespace Pine::Finance {namespace {std::vector<std::string>csvLine(const std::string&line){std::vector<std::string>out;std::string cell;bool quoted=false;for(std::size_t i=0;i<line.size();++i){char c=line[i];if(c=='"'){if(quoted&&i+1<line.size()&&line[i+1]=='"'){cell.push_back('"');++i;}else quoted=!quoted;}else if(c==','&&!quoted){out.push_back(cell);cell.clear();}else cell.push_back(c);}out.push_back(cell);return out;}std::string quote(std::string v){std::string out="\"";for(char c:v){if(c=='\"')out+='\"';out+=c;}return out+'\"';}std::string fingerprint(const std::string&account,const ImportPreviewRow&r){return account+"|"+r.date+"|"+std::to_string(r.amount)+"|"+r.merchant;}bool knownFingerprint(sqlite3*db,const std::string&value){sqlite3_stmt*s{};sqlite3_prepare_v2(db,"SELECT 1 FROM import_fingerprints WHERE fingerprint=?",-1,&s,nullptr);sqlite3_bind_text(s,1,value.c_str(),-1,SQLITE_TRANSIENT);const bool found=sqlite3_step(s)==SQLITE_ROW;sqlite3_finalize(s);return found;}nlohmann::json accountJson(const Account&a){return{{"id",a.id},{"name",a.name},{"type",a.type},{"institution_name",a.institution},{"current_balance_minor",a.currentBalance},{"available_balance_minor",a.availableBalance},{"currency",a.currency},{"archived",a.archived},{"sync_provider",a.syncProvider}};}nlohmann::json transactionJson(const Transaction&t){return{{"id",t.id},{"account_id",t.accountId},{"type",t.type},{"amount_minor",t.amount},{"currency",t.currency},{"merchant",t.merchant},{"original_description",t.originalDescription},{"description",t.description},{"category",t.category},{"date",t.date},{"status",t.status},{"notes",t.notes},{"transfer_id",t.transferId}};}}
ImportExportManager::ImportExportManager(FinanceService&s,FileService&f):service_(s),files_(f){}
namespace {std::string ofxTag(const std::string&block,const std::string&tag){const auto marker="<"+tag+">";auto start=block.find(marker);if(start==std::string::npos)return{};start+=marker.size();auto end=block.find_first_of("<\r\n",start);return block.substr(start,end==std::string::npos?std::string::npos:end-start);}bool knownProvider(sqlite3*db,const std::string&id){if(id.empty())return false;sqlite3_stmt*s{};sqlite3_prepare_v2(db,"SELECT 1 FROM transactions WHERE provider_transaction_id=?",-1,&s,nullptr);sqlite3_bind_text(s,1,id.c_str(),-1,SQLITE_TRANSIENT);const bool found=sqlite3_step(s)==SQLITE_ROW;sqlite3_finalize(s);return found;}}
std::vector<ImportPreviewRow>ImportExportManager::previewCsv(const std::filesystem::path&relative,const std::string&accountId,const CsvMapping&m,std::size_t maxRows)const{auto account=service_.account(accountId);if(!account)throw std::invalid_argument("Import account not found");std::ifstream in(files_.resolve(relative));if(!in)throw std::runtime_error("Unable to open CSV");std::vector<ImportPreviewRow>out;std::string line;if(m.firstRowHeader)std::getline(in,line);while(out.size()<maxRows&&std::getline(in,line)){auto cells=csvLine(line);ImportPreviewRow row;const auto required=std::max({m.date,m.description,m.amount,m.category.value_or(0)});if(cells.size()<=required){row.error="Missing mapped column";out.push_back(row);continue;}row.date=cells[m.date];row.merchant=cells[m.description];row.category=m.category?cells[*m.category]:"Other";auto parsed=parseMoneyMinor(cells[m.amount],Currency::fromCode(account->currency));if(!parsed||*parsed==0){row.error="Invalid amount";out.push_back(row);continue;}row.amount=*parsed;row.valid=row.date.size()==10&&row.date[4]=='-'&&row.date[7]=='-';if(!row.valid)row.error="Date must be YYYY-MM-DD";else row.duplicate=knownFingerprint(service_.database().handle(),fingerprint(accountId,row));out.push_back(std::move(row));}return out;}
ImportResult ImportExportManager::importCsv(const std::filesystem::path&path,const std::string&accountId,const CsvMapping&m,bool confirmed){if(!confirmed)throw std::invalid_argument("Import must be confirmed after preview");ImportResult result;for(auto&r:previewCsv(path,accountId,m,100000)){if(!r.valid){++result.invalid;if(result.errors.size()<20)result.errors.push_back(r.error);continue;}if(r.duplicate){++result.duplicates;continue;}try{const auto type=r.amount<0?"Expense":"Income";service_.addTransaction(accountId,type,std::llabs(r.amount),r.merchant,r.category,r.date);const auto fp=fingerprint(accountId,r);sqlite3_stmt*s{};sqlite3_prepare_v2(service_.database().handle(),"INSERT OR IGNORE INTO import_fingerprints(fingerprint,created_at)VALUES(?,strftime('%s','now')*1000)",-1,&s,nullptr);sqlite3_bind_text(s,1,fp.c_str(),-1,SQLITE_TRANSIENT);sqlite3_step(s);sqlite3_finalize(s);++result.imported;}catch(const std::exception&e){++result.invalid;if(result.errors.size()<20)result.errors.push_back(e.what());}}return result;}
std::vector<ImportPreviewRow>ImportExportManager::previewOfx(const std::filesystem::path&relative,const std::string&accountId,std::size_t maxRows)const{auto account=service_.account(accountId);if(!account)throw std::invalid_argument("Import account not found");std::ifstream in(files_.resolve(relative),std::ios::binary);if(!in)throw std::runtime_error("Unable to open OFX/QFX file");std::string content((std::istreambuf_iterator<char>(in)),{});std::vector<ImportPreviewRow>out;std::size_t position=0;while(out.size()<maxRows&&(position=content.find("<STMTTRN>",position))!=std::string::npos){auto end=content.find("</STMTTRN>",position);if(end==std::string::npos)end=content.find("<STMTTRN>",position+10);auto block=content.substr(position,end==std::string::npos?std::string::npos:end-position);position=end==std::string::npos?content.size():end+10;ImportPreviewRow row;auto rawDate=ofxTag(block,"DTPOSTED");if(rawDate.size()>=8)row.date=rawDate.substr(0,4)+"-"+rawDate.substr(4,2)+"-"+rawDate.substr(6,2);row.merchant=ofxTag(block,"NAME");if(row.merchant.empty())row.merchant=ofxTag(block,"MEMO");row.category="Other";row.providerId=ofxTag(block,"FITID");auto amount=parseMoneyMinor(ofxTag(block,"TRNAMT"),Currency::fromCode(account->currency));if(!amount||*amount==0)row.error="Invalid OFX amount";else if(row.date.size()!=10)row.error="Invalid OFX date";else{row.amount=*amount;row.valid=true;row.duplicate=knownProvider(service_.database().handle(),row.providerId)||knownFingerprint(service_.database().handle(),fingerprint(accountId,row));}out.push_back(std::move(row));}if(out.empty())throw std::runtime_error("No statement transactions found");return out;}
ImportResult ImportExportManager::importOfx(const std::filesystem::path&path,const std::string&accountId,bool confirmed){if(!confirmed)throw std::invalid_argument("Import must be confirmed after preview");ImportResult result;for(auto&r:previewOfx(path,accountId,100000)){if(!r.valid){++result.invalid;continue;}if(r.duplicate){++result.duplicates;continue;}try{auto transaction=service_.addTransaction(accountId,r.amount<0?"Expense":"Income",std::llabs(r.amount),r.merchant,"Other",r.date);sqlite3_stmt*s{};sqlite3_prepare_v2(service_.database().handle(),"UPDATE transactions SET provider_transaction_id=? WHERE id=?",-1,&s,nullptr);sqlite3_bind_text(s,1,r.providerId.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,transaction.id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_step(s);sqlite3_finalize(s);++result.imported;}catch(const std::exception&e){++result.invalid;if(result.errors.size()<20)result.errors.push_back(e.what());}}return result;}
std::filesystem::path ImportExportManager::exportTransactionsCsv(const std::filesystem::path&relative)const{auto path=files_.resolve(relative);std::filesystem::create_directories(path.parent_path());std::ofstream out(path);if(!out)throw std::runtime_error("Unable to create CSV export");out<<"date,merchant,description,category,type,amount_minor,currency,account_id,status,notes\n";std::size_t offset=0;while(true){auto page=service_.transactions("","","","","","","",{}, {},1000,offset);for(auto&t:page)out<<quote(t.date)<<','<<quote(t.merchant)<<','<<quote(t.description)<<','<<quote(t.category)<<','<<quote(t.type)<<','<<t.amount<<','<<quote(t.currency)<<','<<quote(t.accountId)<<','<<quote(t.status)<<','<<quote(t.notes)<<'\n';if(page.size()<1000)break;offset+=page.size();}return path;}
std::filesystem::path ImportExportManager::exportEverythingJson(const std::filesystem::path&relative)const{auto path=files_.resolve(relative);std::filesystem::create_directories(path.parent_path());nlohmann::json root{{"format","pine-finance-export"},{"version",1},{"accounts",nlohmann::json::array()},{"transactions",nlohmann::json::array()},{"budgets",nlohmann::json::array()},{"bills",nlohmann::json::array()},{"subscriptions",nlohmann::json::array()},{"goals",nlohmann::json::array()}};for(auto&a:service_.accounts(true))root["accounts"].push_back(accountJson(a));std::size_t offset=0;while(true){auto page=service_.transactions("","","","","","","",{}, {},1000,offset);for(auto&t:page)root["transactions"].push_back(transactionJson(t));if(page.size()<1000)break;offset+=page.size();}for(auto&b:service_.budgets())root["budgets"].push_back({{"id",b.id},{"category",b.category},{"month",b.month},{"limit_minor",b.limit},{"rollover",b.rollover}});for(auto&b:service_.bills())root["bills"].push_back({{"name",b.name},{"amount_minor",b.amount},{"next_due_date",b.nextDueDate},{"frequency",b.frequency}});for(auto&s:service_.subscriptions(false))root["subscriptions"].push_back({{"name",s.name},{"price_minor",s.price},{"frequency",s.frequency},{"next_charge",s.nextCharge},{"active",s.active}});for(auto&g:service_.goals(true))root["goals"].push_back({{"name",g.name},{"target_amount",g.targetAmount},{"current_amount",g.currentAmount},{"target_date",g.targetDate},{"completed",g.completed}});std::ofstream(path)<<root.dump(2);return path;}
std::filesystem::path ImportExportManager::createBackup(const std::filesystem::path&relative)const{std::scoped_lock lock(const_cast<FinanceDatabase&>(service_.database()).mutex());auto path=files_.resolve(relative);std::filesystem::create_directories(path.parent_path());sqlite3*destination{};if(sqlite3_open(path.string().c_str(),&destination)!=SQLITE_OK)throw std::runtime_error("Unable to create backup");sqlite3_backup*backup=sqlite3_backup_init(destination,"main",service_.database().handle(),"main");if(!backup){sqlite3_close(destination);throw std::runtime_error("Unable to initialize backup");}sqlite3_backup_step(backup,-1);const auto code=sqlite3_backup_finish(backup);sqlite3_close(destination);if(code!=SQLITE_OK)throw std::runtime_error("Backup failed");return path;}
bool ImportExportManager::restoreBackup(const std::filesystem::path&relative,bool confirmed){if(!confirmed)throw std::invalid_argument("Restore must be explicitly confirmed");std::scoped_lock lock(service_.database().mutex());auto path=files_.resolve(relative);sqlite3*source{};if(sqlite3_open_v2(path.string().c_str(),&source,SQLITE_OPEN_READONLY,nullptr)!=SQLITE_OK){if(source)sqlite3_close(source);throw std::runtime_error("Unable to open backup");}sqlite3_stmt*check{};sqlite3_prepare_v2(source,"PRAGMA integrity_check",-1,&check,nullptr);const bool valid=sqlite3_step(check)==SQLITE_ROW&&std::string(reinterpret_cast<const char*>(sqlite3_column_text(check,0)))=="ok";sqlite3_finalize(check);if(!valid){sqlite3_close(source);throw std::runtime_error("Backup integrity check failed");}sqlite3_backup*backup=sqlite3_backup_init(service_.database().handle(),"main",source,"main");if(!backup){sqlite3_close(source);throw std::runtime_error("Unable to initialize restore");}sqlite3_backup_step(backup,-1);const auto code=sqlite3_backup_finish(backup);sqlite3_close(source);if(code!=SQLITE_OK)throw std::runtime_error("Restore failed");return true;}
}
