#include "core/Date.hpp"
#include "ui/Shell.hpp"
#include "finance/Money.hpp"
#include <chrono>
#include <format>
#include <sstream>

namespace Pine {using namespace Finance;namespace {std::string shortError(const std::exception&e){std::string v=e.what();return v.size()>42?v.substr(0,39)+"...":v;}std::int64_t amountOrThrow(const std::string&v,const std::string&currency="USD"){auto parsed=parseMoneyMinor(v,Currency::fromCode(currency));if(!parsed||*parsed<=0)throw std::invalid_argument("Enter a positive monetary amount");return*parsed;}}
void Shell::beginFinanceAccount(const std::string&type){financeDraftType_=type;openTextPrompt("ACCOUNT NAME","",[this](const std::string&name){financeDraftName_=name;openTextPrompt("INSTITUTION (OR MANUAL)","Manual",[this](const std::string&institution){financeDraftInstitution_=institution;openTextPrompt("STARTING BALANCE","0.00",[this](const std::string&amount){financeDraftAmount_=amount;openTextPrompt("CURRENCY","USD",[this](const std::string&currency){try{auto minor=parseMoneyMinor(financeDraftAmount_,Currency::fromCode(currency));if(!minor)throw std::invalid_argument("Invalid starting balance");auto a=finance_.createAccount(financeDraftName_,financeDraftType_,financeDraftInstitution_,*minor,currency);financeSelectedAccount_=a.id;financeView_=FinanceView::AccountDetail;toast("ACCOUNT ADDED");}catch(const std::exception&e){toast(shortError(e));}},InputType::Text,3);},InputType::Number);});});}
void Shell::beginFinanceTransaction(){auto accounts=finance_.accounts();if(accounts.empty()){toast("ADD AN ACCOUNT FIRST");financeTypePicker_=true;return;}if(financeDraftAccount_.empty()){financeDraftAccount_=accounts.front().id;financeDraftType_="Expense";financeTransactionPicker_=true;return;}auto a=finance_.account(financeDraftAccount_);if(!a){financeDraftAccount_.clear();financeTransactionPicker_=true;return;}openTextPrompt("TRANSACTION AMOUNT","",[this,currency=a->currency](const std::string&amount){financeDraftAmount_=amount;openTextPrompt(financeDraftType_=="Income"?"SOURCE":"MERCHANT","",[this,currency](const std::string&merchant){financeDraftName_=merchant;openTextPrompt("CATEGORY","Other",[this,currency](const std::string&category){financeDraftCategory_=category;openTextPrompt("DATE YYYY-MM-DD",FinanceService::today(),[this,currency](const std::string&date){try{finance_.addTransaction(financeDraftAccount_,financeDraftType_,amountOrThrow(financeDraftAmount_,currency),financeDraftName_,financeDraftCategory_,date);financeNotifyBills();toast("TRANSACTION ADDED");financeDraftAccount_.clear();financeDraftAmount_.clear();financeView_=FinanceView::Activity;}catch(const std::exception&e){toast(shortError(e));}},InputType::Text,10);});});},InputType::Number);}
void Shell::beginFinanceTransfer(){auto accounts=finance_.accounts();if(accounts.size()<2){toast("TWO ACCOUNTS ARE REQUIRED");return;}if(financeDraftAccount_.empty()||financeDraftTarget_.empty()){financeDraftAccount_.clear();financeDraftTarget_.clear();financeTransferPicker_=true;return;}auto source=finance_.account(financeDraftAccount_);openTextPrompt("TRANSFER AMOUNT","",[this,currency=source?source->currency:"USD"](const std::string&amount){try{finance_.transfer(financeDraftAccount_,financeDraftTarget_,amountOrThrow(amount,currency),FinanceService::today());toast("TRANSFER COMPLETED");financeDraftAccount_.clear();financeDraftTarget_.clear();financeView_=FinanceView::Activity;}catch(const std::exception&e){toast(shortError(e));}},InputType::Number);}
void Shell::beginFinanceBudget(){openTextPrompt("BUDGET CATEGORY","Food & Dining",[this](const std::string&category){financeDraftCategory_=category;openTextPrompt("MONTHLY LIMIT","",[this](const std::string&amount){try{finance_.setBudget(financeDraftCategory_,FinanceService::currentMonth(),amountOrThrow(amount),false,finance_.settings().budgetWarningPercent);toast("BUDGET CREATED");financeView_=FinanceView::Budget;}catch(const std::exception&e){toast(shortError(e));}},InputType::Number);});}
void Shell::beginFinanceBill(){openTextPrompt("BILL NAME","",[this](const std::string&name){financeDraftName_=name;openTextPrompt("AMOUNT","",[this](const std::string&amount){financeDraftAmount_=amount;openTextPrompt("NEXT DUE YYYY-MM-DD",FinanceService::today(),[this](const std::string&due){financeDraftDate_=due;openTextPrompt("FREQUENCY","Monthly",[this](const std::string&frequency){try{finance_.addBill(financeDraftName_,amountOrThrow(financeDraftAmount_),finance_.accounts().empty()?"":finance_.accounts().front().id,"Utilities",financeDraftDate_,frequency);financeNotifyBills();toast("BILL ADDED");financeView_=FinanceView::Bills;}catch(const std::exception&e){toast(shortError(e));}});},InputType::Text,10);},InputType::Number);});}
void Shell::beginFinanceSubscription(){openTextPrompt("SUBSCRIPTION NAME","",[this](const std::string&name){financeDraftName_=name;openTextPrompt("PRICE","",[this](const std::string&amount){financeDraftAmount_=amount;openTextPrompt("NEXT CHARGE YYYY-MM-DD",FinanceService::today(),[this](const std::string&date){financeDraftDate_=date;openTextPrompt("FREQUENCY","Monthly",[this](const std::string&frequency){try{finance_.addSubscription(financeDraftName_,amountOrThrow(financeDraftAmount_),frequency,finance_.accounts().empty()?"":finance_.accounts().front().id,financeDraftDate_,"Subscriptions");toast("SUBSCRIPTION ADDED");financeView_=FinanceView::Subscriptions;}catch(const std::exception&e){toast(shortError(e));}});},InputType::Text,10);},InputType::Number);});}
void Shell::beginFinanceGoal(){openTextPrompt("GOAL NAME","",[this](const std::string&name){financeDraftName_=name;openTextPrompt("TARGET AMOUNT","",[this](const std::string&amount){financeDraftAmount_=amount;openTextPrompt("TARGET DATE (OPTIONAL)",FinanceService::today(),[this](const std::string&date){try{finance_.addGoal(financeDraftName_,amountOrThrow(financeDraftAmount_),date);toast("GOAL CREATED");financeView_=FinanceView::Goals;}catch(const std::exception&e){toast(shortError(e));}},InputType::Text,10);},InputType::Number);});}
void Shell::beginFinanceImport(){auto accounts=finance_.accounts();if(accounts.empty()){toast("ADD AN ACCOUNT FIRST");return;}financeDraftAccount_=accounts.front().id;financeCsvMapping_=CsvMapping{};openTextPrompt("CSV PATH IN PINE FILES","Documents/Finance/import.csv",[this](const std::string&path){financeDraftName_=path;openTextPrompt("DATE COLUMN NUMBER","1",[this](const std::string&date){try{financeCsvMapping_.date=static_cast<std::size_t>(std::stoul(date)-1);}catch(...){toast("INVALID COLUMN");return;}openTextPrompt("DESCRIPTION COLUMN NUMBER","2",[this](const std::string&description){try{financeCsvMapping_.description=static_cast<std::size_t>(std::stoul(description)-1);}catch(...){toast("INVALID COLUMN");return;}openTextPrompt("AMOUNT COLUMN NUMBER","3",[this](const std::string&amount){try{financeCsvMapping_.amount=static_cast<std::size_t>(std::stoul(amount)-1);}catch(...){toast("INVALID COLUMN");return;}openTextPrompt("CATEGORY COLUMN (0 FOR NONE)","0",[this](const std::string&category){try{auto column=std::stoul(category);financeCsvMapping_.category=column?std::optional<std::size_t>(column-1):std::nullopt;financeImportRows_=financeFiles_.previewCsv(financeDraftName_,financeDraftAccount_,financeCsvMapping_,1000);financeImportPrompt_=true;dismissInput();}catch(const std::exception&e){toast(shortError(e));}},InputType::Number);},InputType::Number);},InputType::Number);},InputType::Number);},InputType::Text,200);}
void Shell::beginFinanceUnlock(){if(!security_.hasDevicePin()){toast("SET A DEVICE PIN IN FINANCE SETTINGS");return;}openTextPrompt("DEVICE PIN","",[this](const std::string&pin){if(financeSecurity_.unlock(pin,SDL_GetTicks()))toast("FINANCE UNLOCKED");else toast("AUTHENTICATION FAILED");},InputType::Password,12);}
void Shell::financeNotifyBills(){financeReminderDay_=SDL_GetTicks()/86400000;const auto settings=finance_.settings();if(!settings.notificationsEnabled)return;std::chrono::sys_days todayPoint;todayPoint=Pine::parseIsoDate(FinanceService::today());for(auto&bill:finance_.bills()){if(!bill.reminderEnabled)continue;std::chrono::sys_days due;try{due=Pine::parseIsoDate(bill.nextDueDate);}catch(const std::invalid_argument&){continue;}const auto days=(due-todayPoint).count();if(days<0||days>bill.reminderDays)continue;const auto privatePreview=settings.hideBalances||!settings.notificationPreviews;const auto body=privatePreview?"You have a bill due soon.":bill.name+" due in "+std::to_string(days)+" day(s): "+financeAmount(bill.amount);notifications_.postOnce("finance-bill-"+bill.id+"-"+bill.nextDueDate,"Finance","Bill reminder",body,!privatePreview);}for(auto&budget:finance_.budgets(FinanceService::currentMonth())){const auto spent=finance_.budgetSpent(budget);if(budget.limit>0&&spent*100>=budget.limit*budget.warningPercent){const auto body=settings.hideBalances||!settings.notificationPreviews?"A budget is approaching its limit.":budget.category+" has used "+std::to_string(spent*100/budget.limit)+"% of its budget.";notifications_.postOnce("finance-budget-"+budget.id+"-"+budget.month,"Finance","Budget warning",body,!settings.hideBalances);}}for(auto&goal:finance_.goals()){if(goal.targetAmount<=0)continue;const int milestone=static_cast<int>(goal.currentAmount*100/goal.targetAmount)/25*25;if(milestone>=25)notifications_.postOnce("finance-goal-"+goal.id+"-"+std::to_string(milestone),"Finance","Savings milestone",settings.hideBalances?"A savings goal reached a milestone.":goal.name+" reached "+std::to_string(milestone)+"%.",!settings.hideBalances);}}
void Shell::acceptanceFinanceView(const std::string&value){if(value=="banks")financeView_=FinanceView::Banks;else if(value=="home")financeView_=FinanceView::Home;else if(value=="accounts")financeView_=FinanceView::Accounts;else if(value=="activity")financeView_=FinanceView::Activity;else if(value=="budget")financeView_=FinanceView::Budget;else if(value=="goals")financeView_=FinanceView::Goals;else if(value=="bills")financeView_=FinanceView::Bills;else if(value=="subscriptions")financeView_=FinanceView::Subscriptions;else if(value=="analytics")financeView_=FinanceView::Analytics;else if(value=="settings")financeView_=FinanceView::Settings;financeScroll_=0;}
bool Shell::acceptanceFinanceExport(){try{financeFiles_.exportTransactionsCsv("Documents/Finance/transactions.csv");financeFiles_.exportEverythingJson("Documents/Finance/finance.json");financeFiles_.createBackup("Documents/Finance/finance-backup.pinefinance");return true;}catch(...){return false;}}
bool Shell::acceptanceFinanceLock(const std::string&pin){if(!security_.hasDevicePin()&&!security_.setDevicePin(pin))return false;auto settings=finance_.settings();settings.requireAuthentication=true;settings.autoLock="Immediately";finance_.saveSettings(settings);financeSecurity_.configure(settings);financeSecurity_.lock();return financeSecurity_.locked();}
}
